### ISSUE TITLE
syntax error when importing tenacity at python 3.7

### ISSUE THREAD

**Issue by b1f6c1c4** [jd/tenacity#117]
`async` becomes keyword since python 3.7, see https://docs.python.org/3.7/whatsnew/changelog.html#changelog and https://bugs.python.org/issue30406

so `from tenacity.async import AsyncRetrying` fails because of syntax error.

**Comment by jcdevil** [comment]
Hello.
Also getting this error (Python 3.6.5)
Stack trace :
```
[ ERROR ] Error in file '/Users/jcdevil/Dev/Forgerock/Stash/PyForge/PyBot/OpenIG/testcases/functional': Importing test library '/Users/jcdevil/Dev/Forgerock/Stash/PyForge/PyBot/OpenIG/testcases/functional/__init__.py' failed: SyntaxError: invalid syntax (_base.py, line 381)
Traceback (most recent call last):
 ...
    from products.servers.Server import Server
  File "<my_path>/Server.py", line 11, in <module>
    from tenacity import retry, stop_after_delay, retry_if_exception_type, wait_fixed
  File "<my_path>/dependencies/lib/python/site-packages/tenacity/__init__.py", line 20, in <module>
    import asyncio
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/Users/jcdevil/Dev/Forgerock/Stash/PyForge/dependencies/lib/python/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
```
