### ISSUE TITLE
Issue with retry_if_exception_type(AssertionError) with python3.6.5

### ISSUE THREAD

**Issue by jcdevil** [jd/tenacity#123]
Hello, issue encountered with Python 3.6.5 and tenacity 4.12.0 (anyway : thx for that nice lib !)

Here is the decorator on my method :
```
    @retry(wait=wait_fixed(2), stop=stop_after_attempt(5), retry=retry_if_exception_type(AssertionError))
```

and when the AssertionError is raised more than supported, I finally get this error :

```
Traceback (most recent call last):
  File "/Users/jcdevil/Dev/DownloadClientHandler.py", line 100, in test_teardown_when_2Gb
    self.wait_for_error_in_logs()
  File "/Users/dependencies/lib/python/site-packages/tenacity/__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "/Users/dependencies/lib/python/site-packages/tenacity/__init__.py", line 330, in call
    start_time=start_time)
  File "/Users/dependencies/lib/python/site-packages/tenacity/__init__.py", line 298, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
```

Thx for help !

**Comment by jd** [comment]
Your traceback is incomplete.

**Comment by jcdevil** [comment]
Reproducing it today, I checked that I do not have anything else :(
Here is a way to reproduce 
```
from tenacity import retry, retry_if_exception_type, wait_fixed, stop_after_attempt

@retry(wait=wait_fixed(2), stop=stop_after_attempt(5), retry=retry_if_exception_type(AssertionError))
def wait_for_error_in_logs():
    raise AssertionError('1 != 0')

if __name__ == '__main__':
    wait_for_error_in_logs()
```

what generates : 

```
15:35 $ python3 /Users/jcdevil/Dev/Stash/PyForge/DEBUG-JC/python_tests/tenacity/test_tenacity.py
Traceback (most recent call last):
  File "/Users/jcdevil/Dev/Stash/PyForge/dependencies/lib/python/site-packages/tenacity/__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "/Users/jcdevil/Dev/Stash/PyForge/DEBUG-JC/python_tests/tenacity/test_tenacity.py", line 7, in wait_for_error_in_logs
    raise AssertionError('1 != 0')
AssertionError: 1 != 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jcdevil/Dev/Stash/PyForge/DEBUG-JC/python_tests/tenacity/test_tenacity.py", line 10, in <module>
    wait_for_error_in_logs()
  File "/Users/jcdevil/Dev/Stash/PyForge/dependencies/lib/python/site-packages/tenacity/__init__.py", line 241, in wrapped_f
    return self.call(f, *args, **kw)
  File "/Users/jcdevil/Dev/Stash/PyForge/dependencies/lib/python/site-packages/tenacity/__init__.py", line 330, in call
    start_time=start_time)
  File "/Users/jcdevil/Dev/Stash/PyForge/dependencies/lib/python/site-packages/tenacity/__init__.py", line 298, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x107ea0c50 state=finished raised AssertionError>]
```

**Comment by jd** [comment]
> Reproducing it today, I checked that I do not have anything else :(

Well, now your traceback is complete. Your original report did not have the exception that was raised.

I'm not sure I understand your problem here. Tenacity retries 5 times, and then gets another exception, so it raises a `RetryError` saying that it did retry but that failed anyway. You can access the last attempt by catching the `RetryError` and accessing its `last_attempt` object.

If you want the original exception to be raised, you can pass `reraise=True`.

**Comment by jcdevil** [comment]
Ah OK ... sorry then ^^
I expected that without `reraise=True`, then no exception would occur after the 5 attempts.
But if I want to do so I will have to catch the `RetryError` in my own `try/except` statement then I presume.
Thx !

**Comment by jd** [comment]
Yes, you have. Failing silently is never a good option (per default). :)
