### ISSUE TITLE
tenacity 5.0.0 breaks compat

### ISSUE THREAD

**Issue by jd** [jd/tenacity#139]
```
gabbi.suitemaker.test_gabbi_resource_create_archive_policy.test_request
-----------------------------------------------------------------------
Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/home/tester/src/.tox/py27-mysql/local/lib/python2.7/site-packages/gabbi/suite.py", line 52, in run
        with fixture.nest([fix() for fix in fixtures]):
      File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/home/tester/src/.tox/py27-mysql/local/lib/python2.7/site-packages/gabbi/fixture.py", line 100, in nest
        six.reraise(exc[0], exc[1], exc[2])
      File "/home/tester/src/.tox/py27-mysql/local/lib/python2.7/site-packages/gabbi/fixture.py", line 86, in nest
        contexts.append(enter_func())
      File "/home/tester/src/.tox/py27-mysql/local/lib/python2.7/site-packages/gabbi/fixture.py", line 45, in __enter__
        self.start_fixture()
      File "gnocchi/tests/functional/fixtures.py", line 168, in start_fixture
        index = indexer.get_driver(conf)
      File "/home/tester/src/.tox/py27-mysql/local/lib/python2.7/site-packages/tenacity/__init__.py", line 292, in wrapped_f
        return self.call(f, *args, **kw)
      File "/home/tester/src/.tox/py27-mysql/local/lib/python2.7/site-packages/tenacity/__init__.py", line 358, in call
        do = self.iter(retry_state=retry_state)
      File "/home/tester/src/.tox/py27-mysql/local/lib/python2.7/site-packages/tenacity/__init__.py", line 318, in iter
        if not (is_explicit_retry or self.retry(retry_state)):
      File "/home/tester/src/.tox/py27-mysql/local/lib/python2.7/site-packages/tenacity/compat.py", line 161, in wrapped_retry_func
        return retry_func(retry_state.outcome)
      File "gnocchi/utils.py", line 354, in __call__
        return super(_retry_on_exception_and_log, self).__call__(attempt)
      File "/home/tester/src/.tox/py27-mysql/local/lib/python2.7/site-packages/tenacity/retry.py", line 67, in __call__
        if retry_state.outcome.failed:
    AttributeError: 'Future' object has no attribute 'outcome'
```

I've deleted the release from PyPI for the time being

**Comment by jd** [comment]
@immerrr If you have time to take a look :)

**Comment by immerrr** [comment]
@jd interesting... so the problem is that there's an override of the retry_if_exception_type class https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/utils.py#L352-L354. Some backward compatibility is provided since it receives an "attempt" instead of a retry_state, but later when it calls the same method of the parent class using the same "attempt" is when it breaks.

To maintain that behaviour we have to have two backward compatibility lanes. One is to allow any retry callback to work with both `retry_state` and whatever it used to accept before (this is done in `BaseRetrying` class and applies for all callbacks). The problem here is that "old-to-new" call signature transition happens in child-parent relationship and skips the `BaseRetrying` class compatibility shim.

So the solution is to make predefined tenacity classes accept both `retry_state` and whatever they used to accept before. This is only done for wait classes right now and i was secretly hoping it could be dumped as well, but probably I'm out of luck in that regard. Brb, fixing.
