### ISSUE TITLE
python3.9/site-packages/tenacity/__init__.py fails on call by Google Assistant - googlesamples-assistant-pushtotalk.py

### ISSUE THREAD

**Issue by Francosf7** [jd/tenacity#348]
Im configuring the Google Assistant on a Raspberry Pi 3 thats running the following Raspberry Pi OS version:

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"

After succesfully linking the device with the Google Application from console.actions.google.com through the Google OAuth service, one must run the following command so that the pushtotalk.py file knows what ids to use everytime the Google Assistant is summoned

googlesamples-assistant-pushtotalk --project-id **my project id** --device-model-id **my model id**

This results in an error that, as I understand it, comes from python3.9/site-packages/tenacity/__init__.py

Full error log:

Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-pushtotalk", line 5, in <module>
    from googlesamples.assistant.grpc.pushtotalk import main
  File "/home/pi/env/lib/python3.9/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 29, in <module>
    from tenacity import retry, stop_after_attempt, retry_if_exception
  File "/home/pi/env/lib/python3.9/site-packages/tenacity/__init__.py", line 292
    from tenacity.async import AsyncRetrying
                  ^
SyntaxError: invalid syntax

**Comment by faam1306** [comment]
Hi, Im having exactly the same issue :c

**Comment by KdbernalO** [comment]
The same for me, I'm having exactly the same issue, i hope a early fix

**Comment by Francosf7** [comment]
The error was solved by upgrading every single google-related dependency inside my virtual python environment (pyenv) and by upgrading tenacity to the latest release (8.0.1)

Here is my full package list:

cachetools               4.2.4
certifi                  2021.10.8
cffi                     1.15.0
charset-normalizer       2.0.12
click                    6.7
enum34                   1.1.10
google-assistant-grpc    0.3.0
google-assistant-library 1.1.0
google-assistant-sdk     0.6.0
google-auth              1.35.0
google-auth-oauthlib     0.5.1
googleapis-common-protos 1.56.0
grpcio                   1.44.0
idna                     3.3
monotonic                1.6
oauthlib                 3.2.0
pathlib2                 2.3.7.post1
pip                      22.0.4
pkg_resources            0.0.0
protobuf                 3.19.4
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.21
requests                 2.27.1
requests-oauthlib        1.3.1
rsa                      4.8
setuptools               61.2.0
six                      1.16.0
sounddevice              0.3.7
tenacity                 8.0.1
urllib3                  1.21.1


But now, this happens:

INFO:root:Transcript of user request: "hello this is a simple  test".
INFO:root:End of audio request detected.
INFO:root:Stopping recording.
INFO:root:Transcript of user request: "hello this is a simple test".
INFO:root:Playing assistant response.
Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-pushtotalk", line 8, in <module>
    sys.exit(main())
  File "/home/pi/env/lib/python3.9/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.9/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.9/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.9/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/env/lib/python3.9/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 458, in main
    continue_conversation = assistant.assist()
  File "/home/pi/env/lib/python3.9/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/home/pi/env/lib/python3.9/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/pi/env/lib/python3.9/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/pi/env/lib/python3.9/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/home/pi/env/lib/python3.9/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 154, in assist
    self.conversation_stream.write(resp.audio_out.audio_data)
  File "/home/pi/env/lib/python3.9/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 326, in write
    buf = normalize_audio_buffer(buf, self.volume_percentage)
  File "/home/pi/env/lib/python3.9/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 57, in normalize_audio_buffer
    buf = arr.tostring()
AttributeError: 'array.array' object has no attribute 'tostring'

**Comment by jbeyoglo** [comment]
Check this video, he shows a solution around minute 15.
He edits ˜/env/lib/python3.9/site-packages/googlesamples/assistant/grpc/audio_helpers.py
line 57 replacing arr.tostring() by arr.tobytes()

**Comment by Francosf7** [comment]
Thanks a lot, Jorge. I found the same solution back then. Still thanks for
taking the time.

I would like to ask you: was my question appropriate for the Tenacity
forum? If not, where should I have asked?
