### ISSUE TITLE
PY_SSIZE_T_CLEAN macro must be defined for '#' formats (Python 3.10)

### ISSUE THREAD

**Issue by carlosost** [jd/tenacity#364]
Sorry if it is a mistake from my side, but according to the stack trace bellow, I understand the error is being thrown by `tenacity`. My first question is: Is latest version of `tenacity` ready for Python 3.10 as described [here](https://docs.python.org/3.10/whatsnew/3.10.html#id2)

If I am not wrong, how could we solve this issue?

Stacktrace:
```
[2022-09-28 WARNING/MainProcess] SystemError
[2022-09-28 WARNING/MainProcess] :
[2022-09-28 WARNING/MainProcess] PY_SSIZE_T_CLEAN macro must be defined for '#' formats

Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 409, in __call__
        result = fn(*args, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/ddtrace/internal/writer.py", line 447, in _send_payload
        response = self._put(payload, headers)
    File "/usr/local/lib/python3.10/site-packages/ddtrace/internal/writer.py", line 399, in _put
        self._conn.request("PUT", self._endpoint, data, headers)
    File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
        self._send_request(method, url, body, headers, encode_chunked)
    File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
    File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
    File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
        self.send(msg)
    File "/usr/local/lib/python3.10/http/client.py", line 975, in send
        self.connect()
    File "/usr/local/lib/python3.10/http/client.py", line 941, in connect
        self.sock = self._create_connection(
    File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
        raise err
    File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
        sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/ddtrace/internal/writer.py", line 564, in flush_queue
        self._retry_upload(self._send_payload, encoded, n_traces)
    File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 406, in __call__
        do = self.iter(retry_state=retry_state)
    File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 363, in iter
        raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f8d1b4de2f0 state=finished raised ConnectionRefusedError>]

[2022-09-28 WARNING/MainProcess] SystemError
[2022-09-28 WARNING/MainProcess] :
[2022-09-28 WARNING/MainProcess] PY_SSIZE_T_CLEAN macro must be defined for '#' formats

```

I am using following Docker images
```
python:3.10-bullseye
redis:alpine
docker.elastic.co/elasticsearch/elasticsearch:7.4.2
memcached:latest
postgres:11.12
```

My requirements.txt (what I think are the most relevant libs for the context of this issue):
```
Django==4.1.1
celery==5.2.7
redis==4.3.4
django-celery-beat==2.1.0
django-celery-results==2.4.0
django-extensions==3.2.1
ddtrace==1.5.0
django-elasticsearch-dsl==7.2.2
elasticsearch<7.14
```

**Comment by jd** [comment]
This is not raised by tenacity. Most likely by a C extension which is not updated for Python 3.10.
