### ISSUE TITLE
Catch exception after retries

### ISSUE THREAD

**Issue by gustavoip** [jd/tenacity#44]
Hey guys,

How can I catch the exception after some unsuccessful tries?

For example:

```
from tenacity import retry, wait_fixed, stop_after_attempt

>>> @retry(stop=stop_after_attempt(5), wait=wait_fixed(1))
... def test():
...     return 1/0
... 
>>> 
>>> try:
...     test()
... except ZeroDivisionError:
...     print("ok")
... 

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tenacity/__init__.py", line 242, in call
    result = fn(*args, **kwargs)
  File "<stdin>", line 3, in test
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tenacity/__init__.py", line 87, in wrapped_f
    return r.call(f, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/tenacity/__init__.py", line 239, in call
    do = self.iter(result=result, exc_info=exc_info)
  File "/usr/local/lib/python3.5/dist-packages/tenacity/__init__.py", line 210, in iter
    six.raise_from(RetryError(fut), fut.exception())
  File "<string>", line 2, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7f2e0f95c940 state=finished raised ZeroDivisionError>]



```

**Comment by jd** [comment]
If you want to catch the `ZeroDivisionError` you should pass `reraise=True` to `@retry()`.

Otherwise you should catch `tenacity.RetryError`.

Note that using reraise in your case will work as expected because the only exception is `ZeroDivisionError`. In the case where different exceptions types could cause a retry, this is more risky.
