### ISSUE TITLE
Bug introduced in tenacity 8.4.0: ModuleNotFoundError: No module named 'tenacity.asyncio'

### ISSUE THREAD

**Issue by MalteEbner** [jd/tenacity#472]
## Description:

Install tenacity 8.4.0 and try to import from it:
```
(.venv) user@device repo % pip install tenacity==8.4                            
Collecting tenacity==8.4
  Using cached tenacity-8.4.0-py3-none-any.whl.metadata (1.2 kB)
Using cached tenacity-8.4.0-py3-none-any.whl (24 kB)
Installing collected packages: tenacity
  Attempting uninstall: tenacity
    Found existing installation: tenacity 8.3.0
    Uninstalling tenacity-8.3.0:
      Successfully uninstalled tenacity-8.3.0
Successfully installed tenacity-8.4.0
(.venv) user@device repo % python -c "import tenacity; print(tenacity.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/malteebnerlightly/Documents/GitHub/lightspeed/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 653, in <module>
    from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100
ModuleNotFoundError: No module named 'tenacity.asyncio'
```

I tried the same on tenacity 8.3.0, it does not have that import error.

Note: This is on python 3.10.8 on macOS Sonoma 14.5 using an M1 Pro. However, it should not matter.

## Reason for error.

The line raising the error was changed in the latest release:
https://github.com/jd/tenacity/blob/702014bc224240c1bb92bdaab250bda178fd938f/tenacity/__init__.py#L653

**Comment by Tenzer** [comment]
#471 already covers the same.
