### ISSUE TITLE
ImportError: No module named 'tasks'

### ISSUE THREAD

**Issue by gabfl** [jd/tenacity#85]
I am getting the following error while installing tenacity 4.4.0. I did not have this error with the previous versions:

## pip install

```
root@2b8b4fe6b21d:~# pip3 install tenacity==4.4.0
Collecting tenacity==4.4.0
  Using cached tenacity-4.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-6dm2lcpa/pbr-3.1.1/setup.py", line 22, in <module>
      File "/tmp/easy_install-6dm2lcpa/pbr-3.1.1/pbr/util.py", line 267, in cfg_to_args
      File "/tmp/easy_install-6dm2lcpa/pbr-3.1.1/pbr/util.py", line 569, in wrap_commands
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'tasks'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2wkcdafj/tenacity/setup.py", line 20, in <module>
        pbr=True)
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 246, in run_setup
        raise
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-6dm2lcpa/pbr-3.1.1/setup.py", line 22, in <module>
      File "/tmp/easy_install-6dm2lcpa/pbr-3.1.1/pbr/util.py", line 267, in cfg_to_args
      File "/tmp/easy_install-6dm2lcpa/pbr-3.1.1/pbr/util.py", line 569, in wrap_commands
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'tasks'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2wkcdafj/tenacity/
```

## Python version

```
root@2b8b4fe6b21d:~# python3 --version
Python 3.5.2
```

## pip list

```
root@2b8b4fe6b21d:~# pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.22.0)
backports.csv (1.0.5)
cffi (1.10.0)
chardet (2.3.0)
cli-helpers (0.2.3)
click (6.7)
configobj (5.0.6)
cryptography (2.0.3)
dbschema (1.1.1)
humanize (0.5.1)
idna (2.6)
mycli (1.12.0)
pgcli (1.7.0)
pgspecial (1.8.0)
pip (9.0.1)
prettytable (0.7.2)
prompt-toolkit (1.0.15)
psycopg2 (2.7.3)
pycparser (2.18)
pycurl (7.43.0)
Pygments (2.2.0)
pygobject (3.20.0)
PyMySQL (0.7.11)
python-apt (1.1.0b1)
PyYAML (3.12)
redis (2.10.5)
requests (2.9.1)
rpq (2.0)
setproctitle (1.1.10)
setuptools (20.7.0)
six (1.10.0)
sqlparse (0.2.3)
ssh-import-id (5.5)
terminaltables (3.1.0)
unattended-upgrades (0.1)
urllib3 (1.13.1)
virtualenv (15.1.0)
wcwidth (0.1.7)
wheel (0.29.0)
root@2b8b4fe6b21d:~# 
```

## Distribution used

```
root@2b8b4fe6b21d:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by gabfl** [comment]
Since the error mentions `pbr` I tried pre-installing it:

```
root@2b8b4fe6b21d:~# pip3 install pbr==3.1.1
Collecting pbr==3.1.1
Downloading pbr-3.1.1-py2.py3-none-any.whl (99kB)
  100% |████████████████████████████████| 102kB 2.0MB/s 
Installing collected packages: pbr
Successfully installed pbr-3.1.1
```

I am still getting the error with tenacity:
```root@2b8b4fe6b21d:~# pip3 install tenacity==4.4.0
Collecting tenacity==4.4.0
  Using cached tenacity-4.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/usr/local/lib/python3.5/dist-packages/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/usr/local/lib/python3.5/dist-packages/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'tasks'
    error in setup command: Error parsing /tmp/pip-build-atkehzws/tenacity/setup.cfg: ImportError: No module named 'tasks'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-atkehzws/tenacity/
```

**Comment by jd** [comment]
Looks like pbr is trying to load an extension installed from somewhere on your system or I don't know what. Try in a virtualenv but I'm sure you won't reproduce it.

```
tenacity $ git grep -c tasks
tenacity $
```

There's nothing referencing any of that in tenacity. It's just a problem with pbr or something that uses is it seems?

**Comment by gabfl** [comment]
Hi Julien,

Thanks for getting back to me! I appreciate it!

When I use a virtualenv, it works (not sure why it would).

I do believe its a pbr issue now.

I cloned your repo and tried to install the package from there and I have the same issue:

```
root@b91c13496aad:~# git clone https://github.com/jd/tenacity
Cloning into 'tenacity'...
remote: Counting objects: 908, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 908 (delta 3), reused 7 (delta 1), pack-reused 892
Receiving objects: 100% (908/908), 207.51 KiB | 0 bytes/s, done.
Resolving deltas: 100% (517/517), done.
Checking connectivity... done.
root@b91c13496aad:~# cd tenacity
root@b91c13496aad:~/tenacity# ls
LICENSE  README.rst  doc  requirements.txt  setup.cfg  setup.py  tenacity  tox.ini
root@b91c13496aad:~/tenacity# python3 setup.py install
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/local/lib/python3.5/dist-packages/pbr/util.py", line 267, in cfg_to_args
    wrap_commands(kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pbr/util.py", line 569, in wrap_commands
    cmdclass = ep.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'tasks'
error in setup command: Error parsing /root/tenacity/setup.cfg: ImportError: No module named 'tasks'
root@b91c13496aad:~/tenacity# 
```

I stripped everything from `setup.cfg`:

```
root@b91c13496aad:~/tenacity# cat setup.py | grep -v '#'

import setuptools

setuptools.setup(
    setup_requires=['pbr'],
    pbr=True)
root@b91c13496aad:~/tenacity# cat setup.cfg | grep -v '#'
[metadata]
name = tenacity
```

I am still able to reproduce the problem with this.

Will investigate further!

**Comment by gabfl** [comment]
The error comes from here: http://git.openstack.org/cgit/openstack-dev/pbr/tree/pbr/util.py#n566

The loop returns modules that cannot be loaded:
```
NameError: name 'pkg_resources' is not defined
>>> import pkg_resources
>>> pkg_resources.iter_entry_points('distutils.commands')
<generator object WorkingSet.iter_entry_points at 0x7f1cd09dcbf8>
>>> for ep in pkg_resources.iter_entry_points('distutils.commands'):
...    print(ep);
... 
lint = tasks:lint
test = tasks:test
lint = tasks:lint
test = tasks:test
docs = tasks:docs
bdist_wheel = wheel.bdist_wheel:bdist_wheel
easy_install = setuptools.command.easy_install:easy_install
install_scripts = setuptools.command.install_scripts:install_scripts
register = setuptools.command.register:register
install_lib = setuptools.command.install_lib:install_lib
alias = setuptools.command.alias:alias
develop = setuptools.command.develop:develop
test = setuptools.command.test:test
egg_info = setuptools.command.egg_info:egg_info
setopt = setuptools.command.setopt:setopt
upload = setuptools.command.upload:upload
bdist_wininst = setuptools.command.bdist_wininst:bdist_wininst
install_egg_info = setuptools.command.install_egg_info:install_egg_info
upload_docs = setuptools.command.upload_docs:upload_docs
build_ext = setuptools.command.build_ext:build_ext
saveopts = setuptools.command.saveopts:saveopts
sdist = setuptools.command.sdist:sdist
build_py = setuptools.command.build_py:build_py
rotate = setuptools.command.rotate:rotate
bdist_egg = setuptools.command.bdist_egg:bdist_egg
install = setuptools.command.install:install
bdist_rpm = setuptools.command.bdist_rpm:bdist_rpm

```

Not a tenacity issue!

Thanks again @jd

**Comment by jd** [comment]
Cool, glad you found the problem!

Indeed those list:
```
lint = tasks:lint
test = tasks:test
lint = tasks:lint
test = tasks:test
docs = tasks:docs
```

Looks suspicious :)

**Comment by mixmastamyk** [comment]
What is the solution?
