### ISSUE TITLE
Installation issue on macOS-10.12.6 (version 4.4.0)

### ISSUE THREAD

**Issue by jcdevil** [jd/tenacity#86]
Hello, I intended to use this pretty cool library but I encountered the following error while installing it on my Mac (Python 2.7.13)
Any help would be much appreciated ! Thx ;)
```
pip install tenacity --user
Collecting tenacity
  Using cached tenacity-4.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/Users/jcdevil/Dev/Forgerock/Stash/PyForge/archives/third_party/lib/python/site-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/Users/jcdevil/Dev/Forgerock/Stash/PyForge/archives/third_party/lib/python/site-packages/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/Users/jcdevil/Dev/Forgerock/Stash/PyForge/archives/third_party/lib/python/site-packages/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/local/lib/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 25, in <module>
        from docutils import nodes
    ImportError: No module named docutils
    error in setup command: Error parsing /private/var/folders/fs/b8r0x9ts6pq9nm_b50rzvwh00000gn/T/pip-build-MtmpTa/tenacity/setup.cfg: ImportError: No module named docutils

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fs/b8r0x9ts6pq9nm_b50rzvwh00000gn/T/pip-build-MtmpTa/tenacity/
```

**Comment by jd** [comment]
Looks like you miss docutils that is required by sphinx. I don't know how your system works and what PyForge is but that looks like a weird installation. :)

**Comment by jcdevil** [comment]
OK It finally worked - Thx for feedback :)
```
pip install tenacity --user
Collecting tenacity
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python2.7/site-packages (from tenacity)
Requirement already satisfied: futures>=3.0; python_version == "2.7" in ./archives/third_party/lib/python/site-packages (from tenacity)
Requirement already satisfied: monotonic>=0.6 in /usr/local/lib/python2.7/site-packages (from tenacity)
Installing collected packages: tenacity
Successfully installed tenacity-4.4.0
```
