### ISSUE TITLE
Can't install Win7 python 2.7.13

### ISSUE THREAD

**Issue by bmeredyk** [jd/tenacity#87]
I'm unable to install via pip or setup.py due to dependency issues with altgraph.compat. Looking at [altgraph's change history](https://pypi.python.org/pypi/altgraph/) it would seem that compat was removed a while ago v0.71.

```
>python setup.py install
> ERROR:root:Error parsing
> Traceback (most recent call last):
>   File "C:\Python27\lib\site-packages\pbr\core.py", line 111, in pbr
>     attrs = util.cfg_to_args(path, dist.script_args)
>   File "C:\Python27\lib\site-packages\pbr\util.py", line 267, in cfg_to_args
>     wrap_commands(kwargs)
>   File "C:\Python27\lib\site-packages\pbr\util.py", line 569, in wrap_commands
>     cmdclass = ep.resolve()
>   File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2297, in
> resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "C:\Python27\lib\site-packages\bbfreeze\__init__.py", line 8, in <module>
> 
>     from bbfreeze.freezer import Freezer
>   File "C:\Python27\lib\site-packages\bbfreeze\freezer.py", line 13, in <module>
> 
>     from modulegraph import modulegraph
>   File "C:\Python27\lib\site-packages\bbfreeze\modulegraph\modulegraph.py", line
>  24, in <module>
>     from altgraph.compat import *
> ImportError: No module named compat
> error in setup command: Error parsing C:\Users\bmeredyk\Downloads\Python\tenacit
> y\tenacity-4.4.0\setup.cfg: ImportError: No module named compat
```

Installing with pip also errors due to altgraph.compat
```
>>pip install tenacity
> Collecting tenacity
>   Using cached tenacity-4.4.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     ERROR:root:Error parsing
>     Traceback (most recent call last):
>       File "c:\python27\lib\site-packages\pbr\core.py", line 111, in pbr
>         attrs = util.cfg_to_args(path, dist.script_args)
>       File "c:\python27\lib\site-packages\pbr\util.py", line 267, in cfg_to_args
> 
>         wrap_commands(kwargs)
>       File "c:\python27\lib\site-packages\pbr\util.py", line 569, in wrap_comman
> ds
>         cmdclass = ep.resolve()
>       File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2297,
>  in resolve
>         module = __import__(self.module_name, fromlist=['__name__'], level=0)
>       File "c:\python27\lib\site-packages\bbfreeze\__init__.py", line 8, in <mod
> ule>
>         from bbfreeze.freezer import Freezer
>       File "c:\python27\lib\site-packages\bbfreeze\freezer.py", line 13, in <mod
> ule>
>         from modulegraph import modulegraph
>       File "c:\python27\lib\site-packages\bbfreeze\modulegraph\modulegraph.py",
> line 24, in <module>
>         from altgraph.compat import *
>     ImportError: No module named compat
>     error in setup command: Error parsing c:\users\bmeredyk\appdata\local\temp\p
> ip-build-8hde6b\tenacity\setup.cfg: ImportError: No module named compat
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in c:\users\bmeredyk
> \appdata\local\temp\pip-build-8hde6b\tenacity\
> 
```

**Comment by jd** [comment]
Looks like a problem with your installation toolchain. Tenacity does not use altgraph.
